#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Kentaro Hoffman

# Short bio or description (displayed in the header)
description: Social Scientist

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar:  ""
#
# Flags below are optional
#

email: khoffm3 <at> uw dot edu
github: https://github.com/khoffm4/
#linkedin: https://www.linkedin.com/in/avisokay/
google_scholar: https://scholar.google.com/citations?user=VScu72IAAAAJ&hl=en


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      image: "assets/media/dp_headshot_longer.jpg"
      layout: "default"

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-148993392-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://khoffm4.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: ''

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
